### ISSUE TITLE
default WAYBACK_BASEURL may be incorrect

### ISSUE THREAD

**Issue by detrout** [internetarchive/brozzler#31]
I installed brozzler via pip and launched it with brozzler-easy in a Debian Jessie VM and was able to scrape a site. (Brozzler 1.1b8, pywb 0.33.0, python3.4)

However the default page links in the dashboard on the job detail page were pointing to http://localhost:8091/brozzler/ As far as I can tell there was nothing started by default listening on port 8091.

After some investigation I found there was something listening on port 8880 that looked like a wayback process, so I tried launching brozzler-easy like this:

WAYBACK_BASEURL=http://192.168.122.152:8880/brozzler brozzler-easy -d warc/ --dashboard-address 0.0.0.0

(the ip addresses were so I could use my regular browser instead of the VM browser to use the site)

Doing that allowed the wayback links to work, but the thumbnail & screenshot urls are still 404ing.

**Comment by detrout** [comment]
Looks like the thumbnails may need VNC, and I hadn't installed that.

**Comment by nlevitt** [comment]
Thanks for the report. https://github.com/internetarchive/brozzler/commit/c3b637d244780b2db201abcdbc3ce2775ea50b5f should fix the WAYBACK_BASEURL mismatch. 

> Doing that allowed the wayback links to work, but the thumbnail & screenshot urls are still 404ing.

I still need to code up some pywb support for thumbnail and screenshot urls. I'll leave this issue open to track that. 

> Looks like the thumbnails may need VNC, and I hadn't installed that.

The vnc thing is for watching the brozzler-controlled browsers in action. You can kinda see how to set that up if you look at ansible/roles/brozzler-worker. It _almost_ but doesn't work out of the box with the vagrant setup (iirc because the vagrant vm's idea of its hostname is not resolvable from outside). In any case, it's not related to the archived thumbnails. (n.b. 8091 vs 8901)

**Comment by detrout** [comment]
I eventually found code in brozzler where it looks like you need to enable warcprox features to get screenshots, but I was archiving a big site didn't get a chance to see if flipping that switch made it work

**Comment by nlevitt** [comment]
> I eventually found code in brozzler where it looks like you need to enable warcprox features to get screenshots, but I was archiving a big site didn't get a chance to see if flipping that switch made it work

Oh, yeah, that too. But even if you get the screenshots I don't think replay will work.

**Comment by nlevitt** [comment]
Added support for screenshot: and thumbnail: urls.
https://github.com/internetarchive/brozzler/commit/5c684779e52fade6ff55a25640447feb75fb6708
Resolving this issue.
